name: flutter_onboarding_slider
description: A page slider with parallex design that allows (Text) widgets or body to slide at a different speed with background.
version: 1.0.11
homepage: https://github.com/adampermana/flutter_onboarding_slider
repository: https://github.com/adampermana/flutter_onboarding_slider.git

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true